### ISSUE TITLE
Should I wait for updates?

### ISSUE THREAD

**Issue by GitStudentSem** [thejustinwalsh/uxp-types#2]
Hey, thank you so much for this repository!
I'm developing a plugin in JS and using jsconfig.json for typing and writing documentation for my project.

As I see, this project has not been updated for a long time, and I do not know if it will be supplemented, for example, core.executeAsModal is not described as a core method.

Of course, I can add it myself to node_modules or make a fork (or somehow separate it), but I would like to leave it as a dependency in case you update it.

Therefore, I would like to know if I can help with something, for example, if I add things in pull requests that I need for the project, but they are not described by you, can you add them?

or is work on these completed and there will be no updates?

**Comment by thejustinwalsh** [comment]
Hey! Glad you find it useful.

I am no longer paying for an Adobe subscription, and the client work I was using this project on has ended.
I won't be able to validate any PRs and test anything out personally, but I am happy to accept any changes that you see necessary.

If you are interested in maintaining a fork, I can archive this repo and forward to yours once it is established.

**Comment by GitStudentSem** [comment]
Oh yeah, okay then, if it's no longer needed I'll leave it alone.
In addition, I found a newer npm package with adobe types that provides everything I need.

But thank you anyway, you did a good job in your time, so good that even after 3 years they were useful =)

**Comment by thejustinwalsh** [comment]
@GitStudentSem, would you mind linking the newer package here in this issue so that others may find it as well?

**Comment by GitStudentSem** [comment]
Well, of course, here are a couple of packages that I managed to find:
```
@adobe/cc-ext-uxp-types
@types/photoshop
```

you need to register this in your jsconfig.json / tsconfig.json file
```
{
   "compilerOptions": {
   // other properties
     "typeRoots": ["node_modules/@types", "node_modules/@adobe/cc-ext-uxp-types"]
   },
   "include": ["src", "global.d.ts"],
   "exclude": ["node_modules", "dist"]
}
```

I also found your typing for Spectrum components, I expanded it a little, but you can supplement it yourself, this is the file global.d.ts

```
declare namespace JSX {
   interface IntrinsicElements {
     "sp-heading": {};
     "sp-divider": { size: "large" };
     "sp-body": { children?: React.ReactNode; class?: string };
     "sp-icon": { children?: React.ReactNode; name?: string; size?: string };
     "sp-detail": { children?: React.ReactNode; class?: string };
     "sp-button-group": { children?: React.ReactNode };
     "sp-button": {
       children?: React.ReactNode;
       style?: React.CSSProperties;
       class?: string;
       disabled?: true | undefine;
       tabindex?: number;
       variant?: string;
       quiet?: string;
       autofocus?: string;
       onClick?: (e: Event) => void;
     };
     "sp-slider": {
       children?: React.ReactNode;
       ref: any;
       "data-part"?: string;
       value: number;
       step?: number;
       min: number;
       max: number;
       variant?: "filled";
       disabled?: true | undefine;
     };
     "sp-label": { children?: React.ReactNode; slot?: string; class?: string };
     "sp-textfield": {
       children?: React.ReactNode;
       ref: any;
       "data-part"?: string;
       type: string;
       value: number;
       min: number;
       max: number;
     };
     "sp-textarea": {
       children?: React.ReactNode;
       style?: React.CSSProperties;
       placeholder: string;
       value: string;
     };
     "sp-progressbar": { max: number; value: number; class?: string };
   }
```
